name: Main CI workflow

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

        ocaml-compiler:
#          - 4.08.x
#          - 4.09.x
#          - 4.10.x
#          - 4.11.x
          - 4.12.x
#          - 4.13.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Setup timeout
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew update
          brew install binutils
          ln -s  `which gtimeout` $HOME/.local/bin/timeout
          echo "$PATH"
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$PATH"
          echo "$PATH:/usr/local/opt/binutils/bin" >> $GITHUB_PATH
          echo "$PATH"
          ls /usr/local/opt/binutils/bin

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build @all

      - run: opam exec -- dune build @runtest
